GET http://localhost:3000/clientes

###
GET http://localhost:3000/clientes/new

###
GET http://localhost:3000/clientes/edit/899

###
GET http://localhost:3000/clientes/delete/899

###
POST http://localhost:3000/clientes/create

###
POST http://localhost:3000/clientes/update

### API URLs
###
GET http://localhost:3000/api/clientes

###
POST http://localhost:3000/api/clientes

###
PUT http://localhost:3000/api/clientes

###
DELETE http://localhost:3000/api/clientes